#!/bin/bash
# ============================================================
# FL3 Dashboard Metrics Updater
# Pulls email list count from GoHighLevel API and updates
# dashboard-data.json + dashboard-data.js, then pushes to GitHub.
#
# Usage: ./update-metrics.sh
# Requires: curl, python3, git
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
JSON_FILE="$SCRIPT_DIR/dashboard-data.json"
JS_FILE="$SCRIPT_DIR/dashboard-data.js"
ENV_FILE="$SCRIPT_DIR/.env"

# ── Load credentials ──
if [ ! -f "$ENV_FILE" ]; then
  echo "Error: .env file not found at $ENV_FILE"
  echo "Create it with:"
  echo "  GHL_API_TOKEN=your-token-here"
  echo "  GHL_LOCATION_ID=your-location-id-here"
  exit 1
fi

source "$ENV_FILE"

if [ -z "$GHL_API_TOKEN" ] || [ -z "$GHL_LOCATION_ID" ]; then
  echo "Error: GHL_API_TOKEN and GHL_LOCATION_ID must be set in .env"
  exit 1
fi

echo "Fetching email list count from GoHighLevel..."

# ── Pull contact count from GHL API ──
RESPONSE=$(curl -s -X GET \
  "https://services.leadconnectorhq.com/contacts/?locationId=$GHL_LOCATION_ID&limit=1" \
  -H "Authorization: Bearer $GHL_API_TOKEN" \
  -H "Version: 2021-07-28" \
  -H "Accept: application/json")

# Extract total from meta.total
TOTAL=$(echo "$RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['meta']['total'])" 2>/dev/null)

if [ -z "$TOTAL" ] || [ "$TOTAL" = "None" ]; then
  echo "Error: Could not get contact count from GHL API"
  echo "Response: $RESPONSE"
  exit 1
fi

echo "Email list count: $TOTAL"

# ── Update dashboard-data.json ──
echo "Updating dashboard-data.json..."

python3 -c "
import json, sys
from datetime import date

with open('$JSON_FILE', 'r') as f:
    data = json.load(f)

# Update the latest week's emailList
weeks = data['metrics']['weeks']
weeks[-1]['emailList'] = $TOTAL

# Update lastUpdated
data['lastUpdated'] = str(date.today())

with open('$JSON_FILE', 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')

print('Updated emailList to $TOTAL in latest metrics week')
"

# ── Regenerate dashboard-data.js ──
echo "Regenerating dashboard-data.js..."

python3 -c "
import json

with open('$JSON_FILE', 'r') as f:
    data = json.load(f)

js = '// Auto-generated by update-metrics.sh. Do not edit manually.\n'
js += 'window.FL3_DASHBOARD_DATA = ' + json.dumps(data, indent=2) + ';\n'

with open('$JS_FILE', 'w') as f:
    f.write(js)

print('Regenerated dashboard-data.js')
"

# ── Git commit and push ──
echo "Pushing to GitHub..."
cd "$SCRIPT_DIR"
git add dashboard-data.json dashboard-data.js
git commit -m "Update email list count to $TOTAL (via GHL API)"
git push

echo ""
echo "Done. Dashboard updated with $TOTAL contacts."
echo "Live at: https://jscott-62.github.io/fl3-dashboard/"
