#!/bin/bash
# ============================================================
# FL3 Dashboard Metrics Updater
# Pulls email list count from GoHighLevel API and updates
# dashboard-data.json + dashboard-data.js, then pushes to GitHub.
#
# Automatically creates a new weekly snapshot if the latest
# week entry is 7+ days old, preserving the previous week
# for week-over-week comparison.
#
# Usage: ./update-metrics.sh
# Requires: curl, python3, git
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
JSON_FILE="$SCRIPT_DIR/dashboard-data.json"
JS_FILE="$SCRIPT_DIR/dashboard-data.js"
ENV_FILE="$SCRIPT_DIR/.env"

# ── Load credentials ──
if [ ! -f "$ENV_FILE" ]; then
  echo "Error: .env file not found at $ENV_FILE"
  echo "Create it with:"
  echo "  GHL_API_TOKEN=your-token-here"
  echo "  GHL_LOCATION_ID=your-location-id-here"
  exit 1
fi

source "$ENV_FILE"

if [ -z "$GHL_API_TOKEN" ] || [ -z "$GHL_LOCATION_ID" ]; then
  echo "Error: GHL_API_TOKEN and GHL_LOCATION_ID must be set in .env"
  exit 1
fi

echo "Fetching email list count from GoHighLevel..."

# ── Pull contact count from GHL API ──
RESPONSE=$(curl -s -X GET \
  "https://services.leadconnectorhq.com/contacts/?locationId=$GHL_LOCATION_ID&limit=1" \
  -H "Authorization: Bearer $GHL_API_TOKEN" \
  -H "Version: 2021-07-28" \
  -H "Accept: application/json")

# Extract total from meta.total
TOTAL=$(echo "$RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['meta']['total'])" 2>/dev/null)

if [ -z "$TOTAL" ] || [ "$TOTAL" = "None" ]; then
  echo "Error: Could not get contact count from GHL API"
  echo "Response: $RESPONSE"
  exit 1
fi

echo "Email list count: $TOTAL"

# ── Update dashboard-data.json (with automatic weekly snapshots) ──
echo "Updating dashboard-data.json..."

python3 -c "
import json
from datetime import date, datetime

JSON_FILE = '$JSON_FILE'
TOTAL = $TOTAL

with open(JSON_FILE, 'r') as f:
    data = json.load(f)

weeks = data['metrics']['weeks']
latest = weeks[-1]
today = date.today()
latest_date = datetime.strptime(latest['date'], '%Y-%m-%d').date()
days_since = (today - latest_date).days

if days_since >= 7:
    # New week: snapshot previous week, create fresh entry
    new_week = {
        'date': str(today),
        'emailList': TOTAL,
        'emailOpenRate': 0,
        'youtubeSubscribers': latest.get('youtubeSubscribers', 0),
        'youtubeViews': 0,
        'adSpend': 0,
        'costPerLead': 0,
        'leads': 0,
        'courseSales': 0,
        'revenue': 0,
        'webinarRegistrations': 0,
        'webinarAttendance': 0
    }
    weeks.append(new_week)
    prev_emails = latest.get('emailList', 0)
    delta = TOTAL - prev_emails
    print(f'Created new week ({today}). Email list: {TOTAL} (+{delta} from last week)')
else:
    # Same week: update in place
    prev_emails = weeks[-2]['emailList'] if len(weeks) >= 2 else 0
    latest['emailList'] = TOTAL
    delta = TOTAL - prev_emails if prev_emails > 0 else 0
    suffix = f' (+{delta} from last week)' if prev_emails > 0 else ''
    print(f'Updated current week ({latest[\"date\"]}). Email list: {TOTAL}{suffix}')

data['lastUpdated'] = str(today)

with open(JSON_FILE, 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
"

# ── Regenerate dashboard-data.js ──
echo "Regenerating dashboard-data.js..."

python3 -c "
import json

with open('$JSON_FILE', 'r') as f:
    data = json.load(f)

js = '// Auto-generated by update-metrics.sh. Do not edit manually.\n'
js += 'window.FL3_DASHBOARD_DATA = ' + json.dumps(data, indent=2) + ';\n'

with open('$JS_FILE', 'w') as f:
    f.write(js)

print('Regenerated dashboard-data.js')
"

# ── Git commit and push ──
echo "Pushing to GitHub..."
cd "$SCRIPT_DIR"
git add dashboard-data.json dashboard-data.js
git commit -m "Update email list count to $TOTAL (via GHL API)"
git push

echo ""
echo "Done. Dashboard updated with $TOTAL contacts."
echo "Live at: https://jscott-62.github.io/fl3-dashboard/"
