#!/usr/bin/env python3
"""
Generates dashboard-data.js from dashboard-data.json.
Embeds referenced .md file contents so markdown previews work on GitHub Pages.

Usage: python3 build-dashboard-js.py
Run from the FL3-Content/metrics/ directory.
"""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
JSON_PATH = os.path.join(SCRIPT_DIR, "dashboard-data.json")
JS_PATH = os.path.join(SCRIPT_DIR, "dashboard-data.js")


def collect_md_paths(data):
    """Extract all .md file paths from the dashboard data."""
    paths = []

    # Launch assets
    for k, v in data.get("launch", {}).get("assets", {}).items():
        if v.get("path") and v["path"].endswith(".md"):
            paths.append(v["path"])

    # Lead magnet assets
    for k, v in data.get("leadMagnet", {}).get("assets", {}).items():
        if v.get("path") and v["path"].endswith(".md"):
            paths.append(v["path"])

    # Weekly content
    for week in data.get("contentSchedule", {}).get("weeklyContent", []):
        for item in week.get("items", []):
            if item.get("path") and item["path"].endswith(".md"):
                paths.append(item["path"])

    # Launch content
    for item in data.get("contentSchedule", {}).get("launchContent", []):
        if item.get("path") and item["path"].endswith(".md"):
            paths.append(item["path"])

    return paths


def resolve_md_path(rel_path):
    """Resolve a relative .md path, trying multiple base directories.

    Paths in dashboard-data.json are relative to FL3-Content/metrics/.
    Some paths (especially lead magnet files) reference directories outside
    FL3-Business-Suite via ../../ which may not resolve correctly.
    This function tries the direct path first, then searches upward.
    """
    # Try direct resolution from SCRIPT_DIR (metrics/)
    direct = os.path.normpath(os.path.join(SCRIPT_DIR, rel_path))
    if os.path.isfile(direct):
        return direct

    # Extract the filename portion after the last known directory
    # and search upward from SCRIPT_DIR for a match
    basename = os.path.basename(rel_path)
    search_dir = SCRIPT_DIR
    for _ in range(6):  # Go up to 6 levels
        search_dir = os.path.dirname(search_dir)
        for root, dirs, files in os.walk(search_dir):
            if basename in files:
                candidate = os.path.join(root, basename)
                # Verify it's likely the right file by checking parent dir name
                parent_dir = os.path.basename(os.path.dirname(rel_path))
                if parent_dir in candidate:
                    return candidate
        # Don't go above the vault root
        if os.path.basename(search_dir) in ("Documents", "Users"):
            break

    return None


def read_md_files(paths):
    """Read .md files and return a dict of path -> content."""
    embedded = {}
    for rel_path in paths:
        resolved = resolve_md_path(rel_path)
        if resolved:
            try:
                with open(resolved, "r", encoding="utf-8") as f:
                    embedded[rel_path] = f.read()
                print(f"  Embedded: {rel_path}")
            except Exception as e:
                print(f"  Warning: Could not read {rel_path}: {e}")
        else:
            print(f"  Skipped (not found): {rel_path}")
    return embedded


def build_js(data, embedded_md):
    """Generate the dashboard-data.js content."""
    data["_embeddedMd"] = embedded_md

    js_content = (
        "// Auto-generated by build-dashboard-js.py. Do not edit manually.\n"
        "// Edit dashboard-data.json instead, then run this script to regenerate.\n"
        "// This file is loaded via <script src> so the dashboard works in file:// mode across all machines.\n"
        "window.FL3_DASHBOARD_DATA = "
        + json.dumps(data, indent=2, ensure_ascii=False)
        + ";\n"
    )
    return js_content


def main():
    os.chdir(SCRIPT_DIR)

    if not os.path.isfile(JSON_PATH):
        print(f"Error: {JSON_PATH} not found.")
        sys.exit(1)

    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    print("Collecting .md file paths...")
    md_paths = collect_md_paths(data)
    print(f"Found {len(md_paths)} referenced .md files.")

    print("Embedding markdown content...")
    embedded_md = read_md_files(md_paths)

    print("Writing dashboard-data.js...")
    js_content = build_js(data, embedded_md)
    with open(JS_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"Done. {len(embedded_md)} files embedded. Output: {JS_PATH}")


if __name__ == "__main__":
    main()
