#!/bin/bash
# ============================================================
# FL3 Dashboard — Weekly Content Sync
# Scans the Weekly-Content subfolders in the Obsidian vault,
# detects new .md files not yet tracked in dashboard-data.json,
# and adds them to the appropriate content folder section.
#
# Folder mapping:
#   Articles/     → articles    (steps: research, write, edit, publish)
#   YouTube/      → youtube     (steps: research, write, film, edit, publish)
#   Social Media/ → social-media (steps: research, write, film, edit, publish)
#   Email/        → email       (steps: research, write, edit, publish)
#
# Usage: ./sync-weekly-content.sh
# Requires: python3, git
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$SCRIPT_DIR/.."
JSON_FILE="$REPO_ROOT/docs/dashboard-data.json"
JS_FILE="$REPO_ROOT/docs/dashboard-data.js"
WEEKLY_DIR="$REPO_ROOT/../../Projects/Weekly-Content"

if [ ! -d "$WEEKLY_DIR" ]; then
  echo "Error: Weekly-Content folder not found at $WEEKLY_DIR"
  exit 1
fi

if [ ! -f "$JSON_FILE" ]; then
  echo "Error: dashboard-data.json not found at $JSON_FILE"
  exit 1
fi

echo "Scanning Weekly-Content folders for new files..."

# ── Scan folders and update dashboard-data.json ──
ADDED=$(python3 << 'PYEOF'
import json, os, re

SCRIPT_DIR = os.environ.get("SCRIPT_DIR", ".")
REPO_ROOT = os.path.join(SCRIPT_DIR, "..")
JSON_FILE = os.path.join(REPO_ROOT, "docs", "dashboard-data.json")
WEEKLY_DIR = os.path.join(REPO_ROOT, "..", "..", "Projects", "Weekly-Content")

# Map disk folder names to dashboard content folder keys
FOLDER_MAP = {
    "Articles": "articles",
    "YouTube": "youtube",
    "Social Media": "social-media",
    "Email": "email",
}

# Steps per folder type
STEPS = {
    "articles": ["research", "write", "edit", "publish"],
    "email":    ["research", "write", "edit", "publish"],
    "youtube":  ["research", "write", "film", "edit", "publish"],
    "social-media": ["research", "write", "film", "edit", "publish"],
}

with open(JSON_FILE, "r") as f:
    data = json.load(f)

wc = data["projects"]["weekly-content"]
folders = wc.setdefault("contentFolders", {})

added_count = 0

for disk_name, folder_key in FOLDER_MAP.items():
    disk_path = os.path.join(WEEKLY_DIR, disk_name)
    if not os.path.isdir(disk_path):
        continue

    # Ensure folder exists in data
    if folder_key not in folders:
        folders[folder_key] = {"label": disk_name, "items": []}
    folder = folders[folder_key]
    items = folder.setdefault("items", [])

    # Collect existing paths for dedup (normalize for comparison)
    existing_paths = set()
    for item in items:
        if item.get("path"):
            existing_paths.add(item["path"])

    # Scan .md files on disk
    for fname in sorted(os.listdir(disk_path)):
        if not fname.endswith(".md"):
            continue

        vault_path = "00-ZenithPro - FL3/Projects/Weekly-Content/" + disk_name + "/" + fname

        if vault_path in existing_paths:
            continue

        # Try to extract title from first # heading in the file
        title = fname[:-3]  # fallback: filename without .md
        try:
            full_path = os.path.join(disk_path, fname)
            with open(full_path, "r", encoding="utf-8") as mdf:
                for line in mdf:
                    line = line.strip()
                    if line.startswith("# ") and not line.startswith("## "):
                        title = line[2:].strip()
                        break
        except Exception:
            pass

        # Build step dict (all false for new items)
        step_keys = STEPS.get(folder_key, ["research", "write", "edit", "publish"])
        steps = {k: False for k in step_keys}

        items.append({
            "title": title,
            "steps": steps,
            "path": vault_path,
        })

        print(f"  + [{disk_name}] {title}")
        added_count += 1

# Update timestamp
from datetime import date
data["lastUpdated"] = str(date.today())

with open(JSON_FILE, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")

print(f"\n{added_count} new item(s) added.")
PYEOF
)

echo "$ADDED"

# Check if anything was added
if echo "$ADDED" | grep -q "0 new item(s) added"; then
  echo "Nothing new to sync."
  exit 0
fi

# ── Regenerate dashboard-data.js ──
echo "Regenerating dashboard-data.js..."

python3 -c "
import json

with open('$JSON_FILE', 'r') as f:
    data = json.load(f)

js = '// Auto-generated by sync-weekly-content.sh. Do not edit manually.\n'
js += 'window.FL3_DASHBOARD_DATA = ' + json.dumps(data, indent=2) + ';\n'

with open('$JS_FILE', 'w') as f:
    f.write(js)

print('Regenerated dashboard-data.js')
"

# ── Git commit and push ──
echo "Pushing to GitHub..."
cd "$REPO_ROOT"
git add docs/dashboard-data.json docs/dashboard-data.js
git commit -m "Sync weekly content: add new files from vault"
git push

echo ""
echo "Done. Dashboard synced."
echo "Live at: https://jscott-62.github.io/fl3-dashboard/"
